defaults:
  - inference_ucond_200m_notri
  - _self_

# Lengths to sample. Uses `nres_lens` if specified, otherwise arange(min_len, max_len+1, step)
nres_lens: 
min_len: 60
max_len: 255
step_len: 5

# Number of samples per protein length
nsamples_per_len: 125 # 250

# Maximum number of samples in each batch
max_nsamples: 8 # 64

# Designability
compute_designability: False

# FID-related metrics
compute_fid: True
metric_factory:
  - metrics: ["FID", "fJSD_C", "fJSD_A", "fJSD_T"]
    ckpt_path: ${oc.env:DATA_PATH}/metric_factory/model_weights/gearnet_ca.pth
    real_features_path: ${oc.env:DATA_PATH}/metric_factory/features/pdb_eval_ca_features.pth
    ca_only: True
    prefix: PDB_
  - metrics: ["FID", "fJSD_C", "fJSD_A", "fJSD_T"]
    ckpt_path: ${oc.env:DATA_PATH}/metric_factory/model_weights/gearnet_ca.pth
    real_features_path: ${oc.env:DATA_PATH}/metric_factory/features/D_FS_eval_ca_features.pth
    ca_only: True
    prefix: AFDB_
  - metrics: ["IS_C", "IS_A", "IS_T"]
    ckpt_path: ${oc.env:DATA_PATH}/metric_factory/model_weights/gearnet_ca.pth
    ca_only: True